version: "3"
services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jenkins/tripdream-back
    container_name: tripdream-back
    ports:
      - 8082:8082
    networks:
      - frontback
    restart: always
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jenkins/tripdream-front
    container_name: tripdream-front
    ports:
      - 8084:80
    depends_on:
      - back
    networks:
      - frontback
    restart: unless-stopped

networks:
  frontback:
