version: "3"
services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jenkins/dapalza-back
    container_name: dapalza-back
    ports:
      - 8082:8082
    networks:
      - frontback
    restart: always
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jenkins/dapalza-front
    container_name: dapalza-front
    ports:
      - 8084:8084
    depends_on:
      - back
    networks:
      - frontback
    restart: unless-stopped

networks:
  frontback:
